<div class="container">

    <h3><?php echo $this->translate('My Order'); ?></h3>
        
    <?php 
        $grand       = 0;
        $lang_suffix = $this->lang === 'AFR' ? '_af' : null;
    ?>

    <div class="table-responsive">
    
        <table class="table table-striped table-item">
        <thead>
        <tr>
            <th><?php echo $this->translate('Student'); ?></th>
            <th><?php echo $this->translate('Item'); ?></th>
            <th><?php echo $this->translate('Price'); ?></th>
            <th><?php echo $this->translate('Qty'); ?></th>
            <th><?php echo $this->translate('Total'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->items as $item): ?>
            <?php $grand += $item['total']; ?>
            <tr>
                <td>
                    <?php if ($item['student_id']): ?>
                        <?php echo $this->escape($item['student_name']); ?>
                    <?php else: ?>
                        N/A
                    <?php endif; ?>
                </td>
                <td><?php echo $this->escape($item['name' . $lang_suffix]); ?></td>
                <td><?php echo $this->currency($item['price']); ?></td>
                <td><?php echo $item['qty']; ?></td>
                <td><?php echo $this->currency($item['total']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4"></th>
            <th><?php echo $this->currency($grand); ?></th>
        </tr>
        </tfoot>
        </table>
        
    </div>
    
    <p>
        <a href="checkout" class="btn btn-default"><?php echo $this->translate('Back to checkout'); ?></a>
    </p> <br>

    <div class="seperator seperator-large"></div>
    
    <h3><?php echo $this->translate('Payment'); ?></h3>
    <p><?php echo $this->translate('Please select your preferred payment method below.'); ?></p> <hr> <br>
    
    <form method="post">
    
        <?php echo $this->form->paytype; ?>
        
        <div id="paytype-info" class="paytype-info">      
            <div class="paytype-info-item" data-type="card">
                <?php echo $this->translate('Visa and Master Card Accepted.'); ?>        
            </div>
            <div class="paytype-info-item" data-type="eft">
                <?php echo $this->translate('Please use your payment reference to make a payment via Electronic Fund Transfer (EFT).'); ?>        
            </div>
        </div>
        
        <?php echo $this->form->submit; ?>
    
    </form>

</div>

<?php echo $this->placeholder('deferred')->captureStart(); ?>
<script>
$(function() {
    $('#paytype').on('change', function() {
        $('.paytype-info-item').css('display', 'none');
        $('.paytype-info-item[data-type="' + $(this).val() + '"]').css('display', 'block');
    }).change()
});
</script>
<?php echo $this->placeholder('deferred')->captureEnd(); ?>