<div class="page-header">

	<h1><?php echo ucfirst($this->type); ?> Vouchers</h1>
	
	<div class="btn-group">
	   <a class="btn btn-info" href="admin/voucher" >Active</a>
	   <a class="btn btn-warning"  href="admin/voucher?redeemed=1" >Redeemed</a>
	   <a class="btn btn-create"  href="<?php echo $this->url(array('action' => 'add')); ?>">Create</a>
	</div>
	
</div>

<?php if ($this->items): ?>

	<table class="datatable">
	<thead>
	<tr>
        <th>Expires</th>
		<th>Code</th>
		<th>Value</th>
		<?php if ($this->type !== 'redeemed'): ?>
		<th class="action nosort"></th>
		<?php endif; ?>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->items as $item): ?>
	<tr>
        <td><?php echo $item['expires'] ? $item['expires'] : 'No'; ?></td>
		<td><?php echo $item['code']; ?></td>
		<td><?php echo $item['amount']; ?><?php echo $item['type'] === 'percent' ? '%' : null; ?></td>
		<?php if ($this->type !== 'redeemed'): ?>
		<td class="action text-center">
			<a class="btn btn-danger btn-delete" href="<?php echo $this->url(array('action' => 'delete', 'code' => $item['code'])); ?>" data-title="<?php echo $this->escape($item['code']); ?>">delete</a>
		</td>
		<?php endif; ?>
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>

<?php else: ?>
	
	<div class="well">Search returned 0 results</div>
	
<?php endif; ?>