<form method="get" action="admin/book">
    
    <div class="pull-left">
        <?php echo $this->btn; ?>
    </div>

    <div class="pull-right">

        <div class="input-group">
        	<input class="form-control" type="search" name="search" value="" autocomplete="off" placeholder="ISBN or Name">
        	<span class="input-group-btn">
        	    <button type="submit" class="btn btn-default">Search</button>
        	</span>
        </div>
	
    </div>

</form>