<div class="container">

    <h2><?php echo sprintf($this->translate('Welcome to %s'), $this->store['Info']->Name . ' ' . $this->translate('Bookshop')); ?></h2>
    
    <div class="seperator"></div> <br>
    
    <h3><?php echo $this->translate('Registration Terms & Conditions'); ?></h3>
    
    <div class="wysiwyg">
        <?php $key = 'TC' . ($this->lang === 'AFR' ? '_AFR' : null); ?>
        <?php echo $this->terms->{$key}; ?>
    </div>
    
    <?php /*
    
    <?php if ($this->specials): ?>

        <h3><?php echo $this->translate('Specials'); ?></h3>
        <div class="product-list">
            <?php echo $this->partial('partial/item-list.phtml', array('items' => $this->specials)); ?>
        </div>
    
    <?php endif; ?>

    */ ?>

</div>