<?php 
	$name 	= $this->element->getName();
	$label 	= $this->element->getLabel();
	$value  = $this->element->getValue() ? $this->element->getValue() : array();
	
	if (isset($this->options['col_right'])) {
	
	    $class = array();
	
	    foreach (explode(' ', $this->options['col_right']) as $col)
	        $class[] = $col;
	    
	    foreach (explode(' ', $this->options['col_left']) as $col) {
	        $size    = explode('-', substr($col, strpos($col, '-', 1) + 1));
	        $class[] = 'col-' . implode('-offset-', $size);
	    }
	
	}
	
?>
<div class="form-group">
    <div<?php echo isset($class) ? ' class="' . implode(' ', $class) . '"' : null; ?>>
        <div class="checkbox">
            <label>
                <input name="<?php echo $name; ?>" value="1" type="checkbox"<?php echo $value == 1 ? ' checked="checked"' : null; ?>> 
                <?php echo $label; ?>
            </label>
        </div>
    </div>
</div>