<div class="container">
    <div class="col-sm-8 col-lg-9 col-sm-push-2 col-lg-push-1">
        <?php if ($this->category): ?>
            <?php $key_name = 'Name_' . $this->lang; ?>
            <h3><?php echo $this->category->{$key_name}; ?></h3>
            
            <div class="product-list">
                <?php echo $this->partial('partial/list-product.phtml', array('items' => $this->items, 'item_class' => 'col-xs-6 col-sm-4', 'item_clearfix' => array(2 => 'visible-xs', 3 => 'visible-sm visible-md visible-lg'))); ?>
            </div>
        <?php endif; ?>
    </div>
</div>