<div class="container">
<?php if ($this->specials): ?>
    
    <?php 
        $key_name = 'Name_' . Zend_Registry::get('LanguageSuffix');
        $key_desc = 'Description_' . Zend_Registry::get('LanguageSuffix');
    ?>

    
<?php endif; ?>
<script>
        jQuery(function(){
            jQuery('#camera_wrap_1').camera({
                thumbnails: false
            });
        });
    </script>
    <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
        <div data-thumb="../images/slides/thumbs/bridge.jpg" data-src="../images/slides/bridge.jpg">
            <div class="camera_caption fadeFromBottom">
                Camera is a responsive/adaptive slideshow. <em>Try to resize the browser window</em>
            </div>
        </div>
        <div data-thumb="../images/slides/thumbs/leaf.jpg" data-src="../images/slides/leaf.jpg">
            <div class="camera_caption fadeFromBottom">
                It uses a light version of jQuery mobile, <em>navigate the slides by swiping with your fingers</em>
            </div>
        </div>
        <div data-thumb="../images/slides/thumbs/road.jpg" data-src="../images/slides/road.jpg">
            <div class="camera_caption fadeFromBottom">
                <em>It's completely free</em> (even if a donation is appreciated)
            </div>
        </div>
        <div data-thumb="../images/slides/thumbs/sea.jpg" data-src="../images/slides/sea.jpg">
            <div class="camera_caption fadeFromBottom">
                Camera slideshow provides many options <em>to customize your project</em> as more as possible
            </div>
        </div>
        <div data-thumb="../images/slides/thumbs/shelter.jpg" data-src="../images/slides/shelter.jpg">
            <div class="camera_caption fadeFromBottom">
                It supports captions, HTML elements and videos and <em>it's validated in HTML5</em> (<a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.pixedelic.com%2Fplugins%2Fcamera%2F&amp;charset=%28detect+automatically%29&amp;doctype=Inline&amp;group=0&amp;user-agent=W3C_Validator%2F1.2" target="_blank">have a look</a>)
            </div>
        </div>
        <div data-thumb="../images/slides/thumbs/tree.jpg" data-src="../images/slides/tree.jpg">
            <div class="camera_caption fadeFromBottom">
                Different color skins and layouts available, <em>fullscreen ready too</em>
            </div>
        </div>
    </div>

    <div class="col-sm-8 col-lg-9 col-sm-push-2 col-lg-push-1">
        <?php if ($this->specials): ?>

        <h3><?php echo $this->translate('Specials'); ?></h3>
        <div class="product-list">
            <?php echo $this->partial('partial/item-list.phtml', array('items' => $this->specials)); ?>
        </div>
    
        <?php endif; ?>
    </div>

    <div class="col-sm-8 col-lg-9 col-sm-push-2 col-lg-push-1">
        <?php if ($this->category): ?>
            <?php $key_name = 'Name_' . $this->lang; ?>
            <h3><?php echo $this->category->{$key_name}; ?></h3>
            
            <div class="product-list">
                <?php echo $this->partial('partial/list-product.phtml', array('items' => $this->items, 'item_class' => 'col-xs-6 col-sm-4', 'item_clearfix' => array(2 => 'visible-xs', 3 => 'visible-sm visible-md visible-lg'))); ?>
            </div>
        <?php endif; ?>
    </div>
</div>