<div class="page-header">

    <?php if (!$this->parent): ?>
	
	   <h1>Categories</h1>
	
	<?php else: ?>
	
		<h1>
			<a href="admin/category-product">Categories</a>
			<small> 
                <?php if ($this->parents): ?>
				<?php foreach($this->parents as $parent): ?>
					\ <a href="<?php echo $this->url(array('action' => 'list', 'parent' => $parent['id']), 'default'); ?>"><?php echo $this->escape($parent['name']); ?></a>
				<?php endforeach; ?>
				<?php endif; ?>
				\ <?php echo $this->escape($this->parent['name']); ?>
			</small>
		</h1>	
	
	<?php endif; ?>
	
	<?php if ($this->create): ?>
	<div class="btn-group">
		<a class="btn btn-create" href="<?php echo $this->url(array('action' => 'add')); ?>">Create</a>
	</div>
	<?php endif; ?>
	
</div>

<?php if ($this->items): ?>

	<table class="datatable ui-sortable" data-sort-url="admin/category-product/sort">
	<thead>
	<tr>
		<th class="nosort">Name</th>
		<th class="action nosort"></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($this->items as $item): ?>
	<tr id="ord-<?php echo $item['id']; ?>" style="cursor: move;">
		<td>
            <?php if ($this->follow): ?>
                <a href="<?php echo $this->url(array('action' => 'list', 'parent' => $item['id']), 'default'); ?>"><?php echo $this->escape($item['name']); ?></a>
            <?php else: ?>
                <?php echo $this->escape($item['name']); ?>
            <?php endif; ?>
        </td>
		<td class="action text-center">
			<a class="btn btn-default btn-edit" href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id'])); ?>">edit</a>
			<a class="btn btn-danger btn-delete" href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id'])); ?>" data-title="<?php echo $this->escape($item['name']); ?>">delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>

<?php else: ?>
	
	<div class="well">Search returned 0 results</div>
	
<?php endif; ?>