<div class="container">

    <h3><?php echo $this->translate('Place an Order'); ?></h3>
    <p><?php echo $this->translate('Choose your child that will recieve the bundles'); ?></p> <br>

    <?php if ($this->auth->AccountType === 'Parent'): ?>
        <div class="form-group">
            <label><?php echo $this->translate('Show bundles for'); ?></label>
            <?php echo $this->formSelect('student', null, array(), $this->children); ?>
        </div>
    <?php endif; ?>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script>
$(function() {
    $('#student').on('change', function() {
        if (!$(this).val())
            return;
        $.getJSON('bundle/set-student', { student: $(this).val() }, function(data) {
            if (data.result === 1) {
                location.href = '<?php echo $this->url(array(), 'bundle-list'); ?>';
            } else {
                displayMessage('An unknown error occurred', 'error');
            }
        });
    });
});
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>