<div class="container">

    <div class="row">
    
        <div class="col-sm-4 col-lg-3">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Bundles'); ?></h3>
                
                <?php $key_name = 'Description_' . $this->lang; ?>
                
                <nav>
                    <ul class="navigation">
                    <?php foreach ($this->bundles as $bundle): ?>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-id="<?php echo $bundle->PriceListID; ?>">
                                <?php echo $this->escape($bundle->{$key_name}); ?>
                            </label>
                        </div>
                        
                    </li>
                    <?php endforeach; ?>
                    </ul>
                </nav>
                
            </div>
            
        </div>
        
        <div class="col-sm-8 col-lg-9">
        
            <h3><?php echo $this->translate('Product Bundles'); ?> - <?php echo $this->escape($this->student->FullName); ?></h3>
            
            <p class="bundles-checked">
                <?php echo $this->translate('If you would like to customise any items in this order please tick the relevant item checkbox.'); ?>
            </p>
            
            <p class="bundles-unchecked">
                <?php echo $this->translate('Please select one or more bundles from the options provided.'); ?>
            </p>
            
            <div class="seperator"></div> <br>
            
            <?php 
                $key_name_b = 'Description_' . $this->lang;
                $key_name_i = 'Name_' . $this->lang;
            ?>
            
            <?php foreach ($this->bundles as $bundle): ?>
            
                <div class="bundle" data-id="<?php echo $bundle->PriceListID; ?>">
            
                    <h4><?php echo $this->escape($bundle->{$key_name_b}); ?></h4>
                
                    <table class="table table-striped table-item">
                    <thead>
                    <tr>
                        <th style="width: 10px;"></th>
                        <th><?php echo $this->translate('Item'); ?></th>
                        <th style="width: 100px;"><?php echo $this->translate('Price'); ?></th>
                        <th style="width: 60px;"><?php echo $this->translate('Qty'); ?></th>
                        <th style="width: 120px;"><?php echo $this->translate('Total'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($bundle->Items as $item): ?>
                        <?php $total = $item->Quantity * $item->Price; ?>
                        <tr data-bid="<?php echo $bundle->PriceListID; ?>" data-sid="<?php echo $item->StockID; ?>" data-type="stock" data-price="<?php echo $item->Price; ?>" data-qty-default="<?php echo $item->Quantity; ?>" data-qty="<?php echo $item->Quantity; ?>" data-total="<?php echo $item->Price; ?>">
                            <td>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" class="customize">
                                    </label>
                                </div>
                            </td>
                            <td>
                                <?php echo $this->escape($item->{$key_name_i}); ?>
                                <span class="tiny">(<?php echo $this->escape($item->Quantity); ?> required)</span>
                            </td>
                            <td><?php echo $this->currency($item->Price); ?></td>
                            <td>
                                <span class="custom-no"><?php echo $item->Quantity; ?></span>
                                <span class="custom hide"><input type="text" name="qty" value="<?php echo $item->Quantity; ?>" maxlength="2" size="4"></span>
                            </td>
                            <td>
                                <span class="total"><?php echo $this->currency($total); ?></span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    </table> <br>
                    
                </div>
            
            <?php endforeach; ?>
            
            <div class="bundles-checked">
            
                <div class="clearfix">
                
                    <h4 class="pull-left">
                        Total: 
                        <span class="grand-total" id="grand-total"></span>
                    </h4>
                
                    <button id="cart-add" class="btn btn-primary cart-add pull-right" data-id="<?php echo $this->product->StockID; ?>" data-type="stock" type="button">
                        <?php echo $this->translate('Add to Cart'); ?>
                    </button>
                
                </div>
            
            </div>
            
        </div>
                                                                            
    </div>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/accounting/accounting.min.js"></script>
<script type="text/javascript" src="js/vendor/tinysort/jquery.tinysort.min.js"></script>
<script>
$(function() 
{

	$('.table > tbody > tr').tsort('td:eq(0)');

    $('nav :checkbox').on('change', function(e) {
    	var $bundle = $('.bundle[data-id="' + $(this).data('id') + '"]');
    	$(this).is(':checked') ? $bundle.show() : $bundle.hide();
    	toggleHelpers();
    	setGrandTotal();
    });

    $(':checkbox.customize').on('click', function(e) {

    	var $tr = $(this).closest('tr');

        if ($(this).is(':checked')) {
            $tr.find('.custom-no').hide();
            $tr.find('.custom').removeClass('hide').find('input').val(0);
        } else {
            $tr.find('.custom-no').show();
            $tr.find('.custom').addClass('hide').find('input').val($tr.data('qty-default'));
        }
        
        setLineTotal($tr);
        
    });

    $('input[name="qty"]').on('focus', function() {
        $(this).attr('data-qty', accounting.formatNumber($(this).val(), 0, ''));
    }).on('blur', function(e) {
        if ($(this).val() != $(this).closest('tr').attr('data-qty'))
     	   setLineTotal($(this).closest('tr'));
    }).on('keypress', function(e) {
    	var keycode = (e.keyCode ? e.keyCode : e.which);
    	if (keycode == '13')
    		setLineTotal($(this).closest('tr'));
    });
    
    $('#cart-add').on('click', function(e) {

        var $data = [], $this = $(this);

    	$('.bundle:visible tr[data-sid]').each(function() {

    	    var $id   = $(this).attr('data-sid'),
    	        $bid  = $(this).attr('data-bid'),
    	        $qty  = $(this).attr('data-qty'),
    	        $type = $(this).attr('data-type');
	        
    	    if (!$id || $qty <= 0)
        	    return;

    	    var $item = { sid: $id, qty: $qty, type: $type, bundle_id: $bid  }

    	    <?php if ($this->auth->AccountType === 'Parent'): ?>
    	    $item.student_id   = '<?php echo $this->student->StudentUniqueRef; ?>';
    	    $item.student_name = '<?php echo $this->student->FullName; ?>';
    	    <?php endif; ?>
    	    
    	    $data.push($item);
    	    
    	});

        $.ajax('cart/add', {
            type: 'post',
        	data: JSON.stringify($data),
        	contentType: 'application/json; charset=UTF-8',
        	beforeSend: function() {
        	    $this.attr('data-text', $this.text()).prop('disabled', 'disabled').text('<?php echo $this->translate('Please wait...'); ?>');
        	} 
        }).done(function(data, status, xhr) {
            if (data.result === 1) {
                displayMessage(data.message, 'success');
            }
        }).always(function() {
        	$this.prop('disabled', false).text($this.attr('data-text'));
        });

        e.preventDefault();
        
    });
    
    toggleHelpers();
});

function setLineTotal(obj)
{
    var $input = obj.find('[name="qty"]'),
        $qty   = accounting.formatNumber($input.val(), 0, '');

    $input.val($qty);

    var $price = accounting.formatNumber(obj.data('price'), 2, '');
    var $total = $price * $qty;

    obj.find('.total').text(accounting.formatMoney($price * $qty, 'R', 2, ' ', ','));
    obj.attr('data-total', $total).attr('data-qty', $qty);

    setGrandTotal();
}

function setGrandTotal()
{
    var $total = 0;
	$('.bundle:visible tr[data-total]').each(function() {
	    $total = $total + parseFloat(accounting.formatNumber($(this).attr('data-total'), 2, ''));
	});
	$('#grand-total').text(accounting.formatMoney($total, 'R', 2, ' ', ','));
}

function toggleHelpers()
{
	$('.bundles-checked, .bundles-unchecked').hide();
	$('.bundle:visible').length ? $('.bundles-checked').show() : $('.bundles-unchecked').show();
}
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>