<div class="container">

    <?php echo $this->navigation()->breadcrumbs()->setPartial('partial/breadcrumbs.phtml'); ?>

    <div class="row article-list">
    
        <div class="col-sm-4 col-lg-3">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Categories'); ?></h3>
                <?php 
                    $navigation = $this->navigation()->findOneById('nav-news');
                    echo $this->navigation()->menu()->renderPartial($navigation, 'partial/sidebar-nav.phtml');
                ?>
            
            </div>
            
        </div>
    
        <div class="col-sm-8 col-lg-9">
        
            <?php if ($this->category): ?>
            
                <h3><?php echo $this->escape($this->category['name']); ?></h3>
            
            <?php else: ?>

                <h3><?php echo $this->escape($this->translate('Latest News')); ?></h3>
            
            <?php endif; ?>
        
            <?php if (count($this->paginator)): ?>
        
                <?php foreach ($this->paginator as $item): ?>
            
                    <?php 
                        $uri = App_Model_BaseCategory::getRouteUri($item['category'], 'nav-news');
                        $url = urldecode($uri . '/' . $item['id']);
                    ?>
            
                    <div class="item">
                    
                        <h4><a href="<?php echo $url; ?>"><?php echo $this->escape($item['name']); ?></a></h4>
                        
                        <div class="item-meta">
                            <i class="fa fa-calendar"></i> <?php echo date('jS F Y', strtotime($item['published'])); ?> 
                        </div>
                        
                        <div class="ellipsis">
                            <p><?php echo App_Util::toSummary($item['description'], array('length' => 350)); ?></p>
                        </div>
                        
                        <a href="<?php echo $url; ?>"><?php echo $this->translate('Read more'); ?>...</a>
                        
                    </div>
                
                <?php endforeach; ?>
                
                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml'); ?>
                
            <?php else: ?>    
                
                <p><?php echo $this->translate('Search returned no results.'); ?></p>
                
            <?php endif; ?>
            
        </div>
                                
    </div>
    
</div>

