<div class="container">

    <h3><?php echo $this->translate('Buy Back Books'); ?></h3>

    <?php if ($this->items): ?>

        <?php $key_name = 'Description_' . $this->lang; ?>
    
        <p>Some description here of what buy back items are and how the user goes about getting them. </p> <br>
        
        <div class="table-responsive" id="BuyBackBooks">
        
            <table class="table table-striped">
            <thead>
            <tr>
                <th><?php echo $this->translate('NAME'); ?></th>
                <th><?php echo $this->translate('ISBN'); ?></th>
                <th><?php echo $this->translate('Price'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->items as $item): ?>
                <tr>
                    <td><?php echo $this->escape($item->Name); ?></td>
                    <td><?php echo $this->escape($item->ISBN); ?></td>
                    <td><?php echo $this->currency($item->_Price); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            </table>
            
        </div>
        <button  type="button" class="btn btn-primary" onclick="printBuyBackBooks();">
                   Print Books
                </button>
    <?php else: ?>
    
        <?php echo $this->translate('Search returned no results'); ?>
    
    <?php endif; ?>

</div>