<div class="container">

    <div class="row"> 
    
        <div class="col-md-6">
        
            <h3><?php echo $this->translate('Contact Form'); ?></h3>
            <p><?php echo $this->translate('Have a question? Complete your details below and we\'ll get back to you.'); ?></p> <hr>
            
            <?php echo $this->form; ?>
                    
        </div>
        
        <div class="col-md-6">
        
            <h3><?php echo $this->translate('Find Us'); ?></h3>
            
            <div id="gmap" class="gmap" data-latlng="<?php echo $this->escape($this->store['Info']->Latitude . ', ' . $this->store['Info']->Longitude); ?>" data-zoom="15"></div> <hr>
        
            <h3><?php echo $this->translate('Address'); ?></h3>
            
            <div class="address">
            
                <address>
                    <strong><?php echo $this->escape($this->store['Info']->Name); ?></strong><br>
                    
                    <?php $address = explode(',' , $this->store['Info']->FullAddress); ?>
                    <?php echo implode('<br>', $address); ?> <br><br>
                    
                    <abbr title="Telephone">T:</abbr> <?php echo $this->escape($this->store['Info']->Telephone); ?> <br>
                    <abbr title="Fax">F:</abbr> <?php echo $this->escape($this->store['Info']->Fax); ?> <br>
                    <abbr title="Email">E:</abbr> <?php echo $this->escape($this->store['Info']->Email); ?>
                </address>
                
            </div>
            
        </div>
        
    </div>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9AEQmS4iUaf3dHTMZEBvv56hLl0jB7AQ"></script>
<script>
$(function() {
    $('#message').prop('rows', 5).css('resize', 'none');
    initMap($('#gmap'));   
});
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>