<?php if ($this->items): ?>

    <table class="table table-striped">
    <tbody>
    <?php foreach ($this->items as $item): ?>
        <tr>
            <td><?php echo $this->escape($item->SubjectName); ?>
            <td class="text-center">
                <a class="btn-subject-remove" href="user/student/subject-remove?reference=<?php echo $this->student->StudentUniqueRef; ?>&subject=<?php echo $this->escape($item->SubjectID); ?>">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    </table>

<?php else: ?>

    <p><?php echo $this->translate('There are currently no subjects assigned to this student.'); ?></p>

<?php endif; ?>