<?php
    $store = App_Session::getInstance()->get('Store');
	
	$this->headTitle($store['Info']->Name . ' ' . $this->translate('Bookshop'))->setSeparator(' | ');
	$this->headLink()
        ->prependStylesheet('css/font-awesome.min.css')
		->prependStylesheet('css/application.css');

	if ($store['theme'])
	    $this->headLink()->appendStylesheet('css/' . $store['theme']);
	
	$this->headMeta()->setName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->doctype();
?>
<html>
<head>
	<base href="<?php echo App_Util::getBaseUrl(); ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link rel="shortcut icon" href="favicon.ico">
	<?php
        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
    ?>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->   
</head>
<body>

<div class="site-wrapper">

    <header class="header">
    
        <div class="container">
        
            <div class="row">
            
                <div class="col-md-4">
                
                    <div class="logo">
                        <?php if ($store['logo']): ?>
                        <img class="img-responsive" src="media/logo/<?php echo $store['logo']; ?>">
                        <?php else: ?>
                        <span><?php echo $store['Info']->Name; ?> <?php echo $this->translate('Bookshop'); ?></span>
                        <?php endif; ?>
                    </div>
                
                </div>
                <div class="col-md-8">
                	
                    <div align="right">
			<table>
			<tr>
			<td align="right" height="20"><h2>
                        <?php if (!Zend_Auth::getInstance()->hasIdentity()): ?>
				 <?php echo ''; ?>
                        <?php else: ?>    
                            <?php echo sprintf($this->translate('Welcome %s', $this->escape(Zend_Auth::getInstance()->getIdentity()->FullName))); ?>  
                        <?php endif; ?>
			</h2<</td>
			</tr>
			<td><div id="Quickclass" class="quick" >		
                        <ul>
                            <?php 
                                $locale     = Zend_Registry::get('Zend_Locale');
                                $switch_to  = $locale->getLanguage() === 'en' ? 'af' : 'en';
                                $switch_txt = $locale->getLanguage() === 'en' ? 'Afrikaans' : 'English';
                            ?>
                            <li>
                                <a href="<?php echo $this->url() . '?lang=' . $switch_to; ?>">
                                    <span class="fa-stack">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-bullhorn fa-stack-1x fa-inverse"></i>
                                    </span>
                                    Switch to <?php echo $switch_txt ?>
                                </a>
                            </li>
                            <li>
                                <a href="checkout">
                                    <span class="fa-stack">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                                    </span>
                                    <?php echo $this->translate('Checkout'); ?>
                                </a>
                            </li>
                            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                                <li>
                                    <a href="<?php echo $this->url(array(), 'account'); ?>">
                                        <span class="fa-stack">
                                            <i class="fa fa-circle fa-stack-2x"></i>
                                            <i class="fa fa-user fa-stack-1x fa-inverse"></i>
                                        </span>
                                        <?php echo $this->translate('My account'); ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array(), 'logout'); ?>">
                                        <span class="fa-stack">
                                            <i class="fa fa-circle fa-stack-2x"></i>
                                            <i class="fa fa-sign-out fa-stack-1x fa-inverse"></i>
                                        </span>
                                        <?php echo $this->translate('Sign out'); ?>
                                    </a>
                                </li>
                            <?php else: ?>
                                <li>
                                    <a href="<?php echo $this->url(array(), 'login'); ?>">
                                        <span class="fa-stack">
                                            <i class="fa fa-circle fa-stack-2x"></i>
                                            <i class="fa fa-sign-in fa-stack-1x fa-inverse"></i>
                                        </span>
                                        <?php echo $this->translate('Sign in'); ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array(), 'register'); ?>">
                                        <span class="fa-stack">
                                            <i class="fa fa-circle fa-stack-2x"></i>
                                            <i class="fa fa-user fa-stack-1x fa-inverse"></i>
                                        </span>
                                        <?php echo $this->translate('Register'); ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul></div>
                    </td>
		    </tr>
		    </table>
                    </div>
                
                </div>
            
            </div>
        
        </div>
        
    </header>

    <div class="navbar">
    
        <div class="container">
        
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-bars fa-2x"></i>
                </button>
            </div>
            
            <nav class="collapse navbar-collapse">
                <?php echo $this->navigation()->menu()->setUlClass('nav navbar-nav')->setMaxDepth(0); ?>
            </nav>
            
        </div>
        
    </div>
    
    <div class="content">
        <?php echo $this->flashMessenger(); ?>
        <?php echo $this->layout()->content; ?>
    </div>
    
    <div class="push"></div>
    
</div>
    
<footer class="footer">

    <div class="container">
    
        <div class="row">
        
            <div class="col-md-4">
            
                <h5><?php echo $this->translate('Contact'); ?></h5> <hr>
                
                <div class="contact">
                
                    <span class="fa-stack">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                    </span>
                    <?php echo $this->escape($store['Info']->Telephone); ?> <hr>
                    
                    <?php $email = $this->escape($store['Info']->Email); ?>
                    <span class="fa-stack">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                    </span>
                    <a href="mailto:<?php echo $email;?>"><?php echo $email; ?></a> <hr>
                    
                </div>
                
            </div>
        
            <?php if (!empty($store['Links'])): ?>
        
            <div class="col-md-4 col-md-offset-4">
        
                <h5><?php echo $this->translate('Links'); ?></h5> <hr>
        
                <ul>
                <?php foreach ($store['Links'] as $item): ?>
                    <li><a href="<?php echo $this->escape($item->LinkURL); ?>"><?php echo $this->escape($item->LinkName); ?></a></li>
                <?php endforeach; ?>
                </ul>
                
            </div>
            
            <?php endif; ?>
        
        </div> <br> 
    
        <div class="clearfix">
    
            <div class="pull-right payment-icons">
                <img src="img/payment/visa.gif" alt="">
                <img src="img/payment/mastercard.gif" alt="">
            </div>
        
            <p class="pull-left copy"><?php echo $this->translate('Copyright'); ?> &copy; <?php echo date('Y'); ?></p>
    
        </div>
    
    </div>
        
</footer>

<div class="site-message" id="site-message"></div>

<div class="modal fade" id="modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content"></div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>
	if (!window.jQuery) {
		document.write('<script src="js/vendor/jquery-1.11.0.min.js"><\/script>');
	}
$( document ).ready(function() {
console.log("Ready");
$('#Quickclass').attr('style', '');
if (navigator.mimeTypes ["application/x-shockwave-flash"] == undefined)
      {
        console.log("Flash is not insalled on your Web browser.");
      }
      else
      {
        console.log("Flash is insalled on your Web browser.");
      }

});
</script>
<script src="js/vendor/bootstrap.min.js"></script>
<script src="js/vendor/jquery.dotdotdot.min.js"></script>
<script src="js/main.js"></script>
<?php echo $this->placeholder('deferred'); ?>

</body>
</html>
