<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sapient Bookstore</title>

    <!-- Bootstrap core CSS -->
    <link href="templates/sapient/css/bootstrap.min.css" rel="stylesheet">

    <link href="templates/sapient/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="templates/sapient/slider-style.css" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
    <div class="header topbar">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="#">Create Account</a></li>
            <li role="presentation"><a href="#">Sign In</a></li>
            <li role="presentation"><a href="#">Cart</a></li>
          </ul>
        </nav>
     </div>

      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="/">HOME</a></li>
            <li role="presentation"><a href="#">NOTICE BOARD</a></li>
            <li role="presentation"><a href="#">CONTACT</a></li>
          </ul>
        </nav>
        <h3 class="text-muted" id="header-text"><img src="templates/sapient/images/logo.png" width="76" height="76"><span style="color:white">SAPIENT</span>BOOKSTORE</h3>

      </div>
      <div class="row">
      	<div class="col-lg-12 border" id="welcome">
      		<h1><span style="color: gray">WELCOME TO</span> <br> SAPIENT BOOKSTORE</h1>
      	</div>
      </div>
      <div class="row">
        <div class="col-lg-12 border">
          <ul id="slideshow">
          <?php foreach ($this->books as $book) { ?>
            <li>
              <h3><?php echo $book->Name; ?></h3>
              <span><?php echo $book->ImageURLBig; ?></span>
              <p><?php echo $book->Description_ENG; ?></p>
              <a href="#"><img src="<?php echo $book->ImageURLSmall; ?>" alt="<?php echo $book->Name; ?>" /></a>
            </li>
          <?php }?>
          </ul>
          <div id="wrapper">
            <div id="fullsize">
              <div id="imgprev" class="imgnav" title="Previous Image"></div>
              <div id="imglink"></div>
              <div id="imgnext" class="imgnav" title="Next Image"></div>
              <div id="image"></div>
              <div id="information">
                <h3></h3>
                <p></p>
              </div>
            </div>
            <div id="thumbnails">
              <div id="slideleft" title="Slide Left"></div>
              <div id="slidearea">
                <div id="slider"></div>
              </div>
              <div id="slideright" title="Slide Right"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="row marketing">
        <div class="col-lg-4">
          <img src="templates/sapient/images/sapient-featured.png">
        </div>

        <div class="col-lg-4">
          <img src="templates/sapient/images/sapient-catalogue.png">
        </div>

        <div class="col-lg-4">
          <img src="templates/sapient/images/sapient-books.png">
        </div>
      </div>

      <footer class="footer">
        <p>&copy; Sapient Bookstore 2014</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="templates/sapient/js/ie10-viewport-bug-workaround.js"></script>
    
    <script type="text/javascript" src="templates/sapient/compressed.js"></script>
    <script type="text/javascript">
      $('slideshow').style.display = 'none';
      $('wrapper').style.display = 'block';
      var slideshow=new TINY.slideshow("slideshow");
      window.onload=function(){
        slideshow.speed = 5;
        slideshow.link = "linkhover";
        slideshow.info = "information";
        slideshow.thumbs = "slider";
        slideshow.left = "slideleft";
        slideshow.right = "slideright";
        slideshow.scrollSpeed = 4;
        slideshow.spacing = 5;
        slideshow.active = "#fff";
        slideshow.init("slideshow", "image", "imgprev", "imgnext", "imglink");
      }
    </script>
  </body>
</html>
