<div class="container">

    <div class="row">
    
        <div class="col-sm-8 col-lg-9 col-sm-push-4 col-lg-push-3">
        
            <?php if ($this->category): ?>
            
                <?php $key_name = 'Name_' . $this->lang; ?>
            
                <h3><?php echo $this->category->{$key_name}; ?></h3>
                
                <div class="product-list">
                    <?php echo $this->partial('partial/item-list.phtml', array('items' => $this->items, 'item_class' => 'col-xs-6 col-sm-4', 'item_clearfix' => array(2 => 'visible-xs', 3 => 'visible-sm visible-md visible-lg'))); ?>
                </div>
            
            <?php endif; ?>
        
        </div>
        
        <div class="col-sm-4 col-lg-3 col-sm-pull-8 col-lg-pull-9">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Categories'); ?></h3>
                <?php echo $this->navigation()->menu()->renderPartial($this->nav, 'partial/sidebar-nav.phtml'); ?>
                
            </div>
            
        </div>
        
    </div>

</div>