<div class="container">

    <div class="row">
    
        <div class="col-sm-8 col-lg-9 col-sm-push-4 col-lg-push-3">
        
            <div class="row product-view">
            
                <div class="col-sm-4">
                    <div class="item-image">
                        <?php echo $this->image64($this->product->ProductImage); ?>
                    </div>
                </div>
            
                <div class="col-sm-8">
                
                    <?php 
                        $key_name = 'Name_' . $this->lang;
                        $key_desc = 'Description_' . $this->lang;
                    ?>
                
                    <h3><?php echo $this->escape($this->product->{$key_name}); ?></h3>
                    <h4><?php echo $this->currency($this->product->Price); ?></h4>
                    
                    <p><?php echo $this->escape($this->product->{$key_desc}); ?></p>
                    
                    <hr>
                    
                    <button id="cart-add" class="btn btn-primary cart-add" data-id="<?php echo $this->product->StockID; ?>" data-type="stock" type="button">
                        <?php echo $this->translate('Add to Cart'); ?>
                    </button>
                    
                </div>
                
            </div>
        
        </div>
        
        <div class="col-sm-4 col-lg-3 col-sm-pull-8 col-lg-pull-9">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Categories'); ?></h3>
                <?php echo $this->navigation()->menu()->renderPartial($this->nav, 'partial/sidebar-nav.phtml'); ?>
                
            </div>
            
        </div>
        
    </div>

    <?php // Zend_Debug::dump($this->product); ?>

</div>