<div class="container">

    <div class="row">
    
        <div class="col-sm-4 col-lg-3">
        
            <div class="sidebar">
        
                <h3><div id="sidebarHeader"><?php echo $this->translate('Bundles'); ?><div></h3>
                <?php echo $this->navigation()->menu()->renderPartial($this->nav, 'partial/sidebar-nav.phtml'); ?>
                
            </div>
            
        </div>
        
        <div class="col-sm-8 col-lg-9">
        
            <h3><?php echo $this->translate('Place an Order'); ?> - <?php echo $this->escape($this->student->FullName); ?></h3>
            <p><?php echo $this->translate('Please select a bundle from the options provided.'); ?></p>
            <div id="ResultContent"></div>
	 <button id="cart-add" type="button" class="btn btn-primary">
                    <?php echo $this->translate('Add To Cart'); ?>
                </button>
 		<button  type="button" class="btn btn-primary" onclick="printOrder();">
                   Print Order
                </button>
        </div>
                                                                            
    </div>

</div>
<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/accounting/accounting.min.js"></script>
<script>
$(function() {

    $('input[name="qty"]').on('focus', function() {
        $(this).attr('data-qty', accounting.formatNumber($(this).val(), 0, ''))
    }).on('blur', function(e) {
        if ($(this).val() != $(this).closest('tr').attr('data-qty'))
     	   setQty($(this));
    }).on('keypress', function(e) {
    	var keycode = (e.keyCode ? e.keyCode : e.which);
    	if (keycode == '13')
        	setQty($(this));
    });

    $('#customize').on('click', function(e) {
        e.preventDefault();
        $('.custom-no').hide();
        $('.custom').removeClass('hide').find('input').val(0);
        setItemTotals();
    });
    
    $('#cart-add').on('click', function(e) {

        var $data = [], $this = $(this);

    	$('tr[data-sid]').each(function() {

    	    var $id  = $(this).attr('data-sid'),
    	        $qty = $(this).attr('data-qty');
	    var $bundleID = $(this).attr('data-bid');	
    	    
    	    if (!$id || $qty <= 0)
        	    return;

    	    var $item = { sid: $id, qty: $qty, type: 'stock', bundle_id: $bundleID  }

    	    <?php if ($this->auth->AccountType === 'Parent'): ?>
    	    $item.student_id   = '<?php echo $this->student->StudentUniqueRef; ?>';
    	    $item.student_name = '<?php echo $this->student->FullName; ?>';
    	    <?php endif; ?>
    	    
    	    $data.push($item);
    	    
    	});

        $.ajax('cart/add', {
            type: 'post',
        	data: JSON.stringify($data),
        	contentType: 'application/json; charset=UTF-8',
        	beforeSend: function() {
        	    $this.attr('data-text', $this.text()).prop('disabled', 'disabled').text('<?php echo $this->translate('Please wait...'); ?>');
        	} 
        }).done(function(data, status, xhr) {
            if (data.result === 1) {
                displayMessage(data.message, 'success');
            }
        }).always(function() {
        	$this.prop('disabled', false).text($this.attr('data-text'));
        });

        e.preventDefault();
        
    });
    
});
function setQty(obj)
{
    var $tr    = obj.closest('tr'),
        $input = $tr.find('[name="qty"]'),
        $qty   = accounting.formatNumber($input.val(), 0, '');

    $input.val($qty);
    
    var $price = accounting.formatNumber($tr.data('price'), 2, '');
    var $total = $price * $qty;
    
    $tr.find('.total').text(accounting.formatMoney($price * $qty, 'R', 2, ' ', ','));
    $tr.attr('data-total', $total).attr('data-qty', $qty);
    setTotal();
}
function setTotal()
{
    var $total = 0;
	$('tr[data-total]').each(function() {
	    $total = $total + parseFloat(accounting.formatNumber($(this).attr('data-total'), 2, ''));
	});
	$('#grand-total').text(accounting.formatMoney($total, 'R', 2, ' ', ','));
}
function setItemTotals()
{
	$('input[name="qty"]').trigger('blur');
}
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>
