<div class="container">

    <div class="row">
    
        <div class="col-sm-8 col-lg-9 col-sm-push-4 col-lg-push-3">
        <div id="CartToPrint">
            <?php $key_name = 'Description_' . $this->lang; ?>
            <h3><?php echo $this->escape($this->bundle->{$key_name}); ?> - <?php echo $this->escape($this->student->FullName); ?></h3>
        
            <?php if ($this->items): ?>

                <p><?php echo sprintf($this->translate('If you would like to customise the items in this bundle please %s.'), '<a id="customize" href="javascript:;">' . $this->translate('click here') . '</a>'); ?></p>
            
                <?php $grand = 0; ?>
		
                <table class="table table-striped table-item">
                <thead>
                <tr>
                    <th><?php echo $this->translate('Item'); ?></th>
                    <th><?php echo $this->translate('Price'); ?></th>
                    <th><?php echo $this->translate('Qty'); ?></th>
                    <th><?php echo $this->translate('Total'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->items as $item): ?>
                    <?php 
                        $total  = $item->Quantity * $item->Price;
                        $grand += $total;
                        
                        $key_name = 'Name_' . $this->lang;
                    ?>
                    <tr data-bid="<?php echo $this->bundle->PriceListID; ?>" data-sid="<?php echo $item->StockID; ?>" data-price="<?php echo $item->Price; ?>" data-qty="<?php echo $item->Quantity; ?>" data-total="<?php echo $item->Price; ?>" data-ISBN="<?php echo $item->ISBN; ?>">
                        <td>
                            <?php echo $this->escape($item->{$key_name}); ?>
                            <span class="tiny">(<?php echo $this->escape($item->Quantity); ?> required)</span>
                        </td>
                        <td><?php echo $this->currency($item->Price); ?></td>
                        <td>
                            <span class="custom-no"><?php echo $item->Quantity; ?></span>
                            <span class="custom hide"><input type="text" name="qty" value="<?php echo $item->Quantity; ?>" maxlength="2" size="4"></span>
                        </td>
                        <td>
                            <span class="total"><?php echo $this->currency($total); ?></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="3"></th>
                    <th>
                        <span class="grand-total" id="grand-total"><?php echo $this->currency($grand); ?></span>
                    </th>
                </tr>
                </tfoot>
                </table> <br>
                
               
                </div>
            <?php endif; ?>
            
        </div>
        
        <div class="col-sm-4 col-lg-3 col-sm-pull-8 col-lg-pull-9">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Bundles'); ?></h3>
                <?php echo $this->navigation()->menu()->renderPartial($this->nav, 'partial/sidebar-nav.phtml'); ?>
                
            </div>
            
        </div>
                                                                            
    </div>

</div>
<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/accounting/accounting.min.js"></script>
<script>
$(function() {

    $('input[name="qty"]').on('focus', function() {
        $(this).attr('data-qty', accounting.formatNumber($(this).val(), 0, ''))
    }).on('blur', function(e) {
        if ($(this).val() != $(this).closest('tr').attr('data-qty'))
     	   setQty($(this));
    }).on('keypress', function(e) {
    	var keycode = (e.keyCode ? e.keyCode : e.which);
    	if (keycode == '13')
        	setQty($(this));
    });

    $('#customize').on('click', function(e) {
        e.preventDefault();
        $('.custom-no').hide();
        $('.custom').removeClass('hide').find('input').val(0);
        setItemTotals();
    });
    
    $('#cart-add').on('click', function(e) {

        var $data = [], $this = $(this);

    	$('tr[data-sid]').each(function() {

    	    var $id  = $(this).attr('data-sid'),
    	        $qty = $(this).attr('data-qty');
	    var $bid = $(this).attr('data-bid');
    	    
    	    if (!$id || $qty <= 0)
        	    return;

    	    var $item = { sid: $id, qty: $qty, type: 'stock', bundle_id: $bid  }

    	    <?php if ($this->auth->AccountType === 'Parent'): ?>
    	    $item.student_id   = '<?php echo $this->student->StudentUniqueRef; ?>';
    	    $item.student_name = '<?php echo $this->student->FullName; ?>';
    	    <?php endif; ?>
    	    
    	    $data.push($item);
    	    
    	});

        $.ajax('cart/add', {
            type: 'post',
        	data: JSON.stringify($data),
        	contentType: 'application/json; charset=UTF-8',
        	beforeSend: function() {
        	    $this.attr('data-text', $this.text()).prop('disabled', 'disabled').text('<?php echo $this->translate('Please wait...'); ?>');
        	} 
        }).done(function(data, status, xhr) {
            if (data.result === 1) {
                displayMessage(data.message, 'success');
            }
        }).always(function() {
        	$this.prop('disabled', false).text($this.attr('data-text'));
        });

        e.preventDefault();
        
    });
    
});
function setQty(obj)
{
    var $tr    = obj.closest('tr'),
        $input = $tr.find('[name="qty"]'),
        $qty   = accounting.formatNumber($input.val(), 0, '');

    $input.val($qty);
    
    var $price = accounting.formatNumber($tr.data('price'), 2, '');
    var $total = $price * $qty;
    
    $tr.find('.total').text(accounting.formatMoney($price * $qty, 'R', 2, ' ', ','));
    $tr.attr('data-total', $total).attr('data-qty', $qty);
    setTotal();
}
function setTotal()
{
    var $total = 0;
	$('tr[data-total]').each(function() {
	    $total = $total + parseFloat(accounting.formatNumber($(this).attr('data-total'), 2, ''));
	});
	$('#grand-total').text(accounting.formatMoney($total, 'R', 2, ' ', ','));
}
function setItemTotals()
{
	$('input[name="qty"]').trigger('blur');
}
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>
<?php $this->headTitle($this->translate('Bundles')); ?>