<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span>&times;</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title"><?php echo $this->escape($this->student->FullName); ?> - <?php echo $this->translate('Subject Management'); ?></h4>
</div>
<div class="modal-body">

    <div class="clearfix" style="padding: 8px; background-color: #F5F5F5;">

        <form class="ajax-form form-inline pull-right" method="post" action="user/student/subject-add?reference=<?php echo $this->student->StudentUniqueRef; ?>">
        
            <div class="form-group">
                <?php echo $this->formSelect('subject', null, array(), $this->subjects); ?>
            </div>
            
            <button class="btn btn-primary" type="submit" id="btn-subject-add"><?php echo $this->translate('Add'); ?></button>
            
        </form>
    
    </div>

    <hr>
    
    <div id="subject-list"></div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
</div>

<script>
$(function() {

    $(document).on('click', '.btn-subject-remove', function(e) {
        e.preventDefault();
        $(this).text('processing...');
        $.getJSON($(this).attr('href'), function(data) {
            if (data.callback)
            	evalCallback(data.callback);
        });
    });

    subjectList();
    
});
function subjectList()
{
	$('#subject-list').load('user/student/subject-list?reference=<?php echo $this->student->StudentUniqueRef; ?>');	
}
</script>