<div class="container">

    <div class="row">
    
        <div class="sidebar col-sm-3">
            <?php 
                $navigation = $this->navigation()->findOneById('nav-account');
                echo $this->navigation()->menu()->renderPartial($navigation, array('partial/sidebar-nav.phtml', 'default'));
            ?>
        </div>
        
        <div class="col-sm-9">
        
            <h3><?php echo $this->translate('My Profile'); ?></h3>
            <p><?php echo $this->translate('Changes can be made to your details below.')?></p>
            
            <div class="seperator"></div>
            
            <?php echo $this->form; ?>
        
        </div>
        
    </div>

</div>