<div class="container">
 <h4><?php 
//echo $this->lang;
//Zend_Debug::dump($this->items);
 if($this->lang === "AFR")
{
 echo $this->terms["TC_AFR"];
}
else
{
 echo $this->terms["TC_ENG"]; 
}
  ?> </h4>     
    <h3><?php echo $this->translate('Buy Back Books'); ?></h3>

    <?php if ($this->items): ?>

        <?php // $key_name = 'Description_' . $this->lang; ?>
    
        <p>Some description here of what buy back items are and how the user goes about getting them.</p> <br>
        <div id="print-area">
        <table class="table table-striped table-item" >
        <thead>
        <tr>
            <th><?php echo $this->translate('Name'); ?></th>
            <th><?php echo $this->translate('ISBN'); ?></th>
            <th><?php echo $this->translate('Price'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->items as $item): ?>
            <tr>
                <td><?php echo $this->escape($item->Name); ?></td>
                <td><?php echo $this->escape($item->ISBN); ?></td>
                <td><?php echo $this->currency($item->_Price); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
        </div>
        <div class="text-right">
            <a href="javascript:;" class="btn btn-primary btn-print"><?php echo $this->translate('Print'); ?></a>
        </div>
        
    <?php else: ?>
    
        <?php echo $this->translate('Search returned no results'); ?>
    
    <?php endif; ?>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/jquery.print.js"></script>
<script>
$(function() {
    $('.btn-print').on('click', function(e) {
        e.preventDefault();
	printBuyBackBooks();
       // $('#print-area').print();
    });
});
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>