<div class="container">

<?php if (APPLICATION_ENV !== 'production'): ?>

    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>
    
    <?php if (isset($this->exception)): ?>
    
        <h3>Exception information:</h3>
        <p><b>Message:</b> <?php echo $this->exception->getMessage(); ?></p>
        
        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString(); ?></pre>
        
        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)); ?></pre>
    
    <?php endif; ?>
    
<?php else: ?>

    <h3>Oops! Page not found</h3>
    <p>The page you are requesting does not exist.</p>    
    
<?php endif; ?>

</div>