<div class="modal-body">
    
    <?php if ($this->items): ?>
    
        <table class="table table-striped">
        <thead>
        <tr>
            <th>Student</th>
            <th>Item</th>
            <th>Qty</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->items as $item): ?>
        <tr>
            <td><?php echo $item->Student ? $this->escape($item->Student) : 'N/A'; ?></td>
            <td><?php echo $this->escape($item->ItemDescription); ?></td>
            <td><?php echo $this->escape($item->Quantity); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
    
    <?php else: ?>
    
        <p><?php echo $this->translate('There are no items in this order.'); ?></p>
    
    <?php endif; ?>
    
    <?php //Zend_Debug::dump($this->items); ?>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
</div>