<div class="container">

    <div class="row">
    
        <div class="sidebar col-sm-3">
            <?php 
                $navigation = $this->navigation()->findOneById('nav-account');
                echo $this->navigation()->menu()->renderPartial($navigation, array('partial/sidebar-nav.phtml', 'default'));
            ?>
        </div>
        
        <div class="col-sm-9">
        
            <h3><?php echo $this->translate('Order History'); ?></h3>
        
            <?php if ($this->orders): ?>
            
            <div class="table-responsive">
            
                <table class="table table-striped">
                <thead>
                <tr>
                    <th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('Reference'); ?></th>
                    <th><?php echo $this->translate('Payment Reference'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                    <th></th>
                </tr> 
                </thead>
                <tbody>
                <?php foreach ($this->orders as $item): ?>
                <?php //Zend_Debug::dump($item); ?>
                <tr>
                    <td><?php echo date('Y-m-d', $item->DateTime / 1000)?></td>
                    <td><?php echo $this->escape($item->OrderRef); ?></td>
                    <td><?php echo $this->escape($item->PaymentReference); ?></td>
                    <td><?php echo $this->escape($item->OrderState); ?></td>
                    <td class="text-center">
                        <a href="user/account/history-item?order=<?php echo $item->OrderRef; ?>" data-toggle="modal" data-target="#modal">
                            <span class="fa-stack">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-list fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>           
                </table>
                
            </div>
            
            <?php else: ?>
            
                <p><?php echo $this->translate('You have not placed any orders with us recently.'); ?>
            
            <?php endif; ?>
        
        </div>
        
    </div>

</div>