<?php 

    $action = 'user/student/add';
    $params = $this->params;
    
    if ($params && is_array($params)) {
        
        if (isset($params['edit']))
            $edit = true;
        
        if (isset($params['action']))
            $action = $params['action'];
        
    }

?>

<form class="ajax-form" method="post" action="<?php echo $action; ?>">

    <div class="row">
        <div class="col-sm-6"><?php echo $this->form->Name; ?></div>
        <div class="col-sm-6"><?php echo $this->form->Surname; ?></div>
    </div>
    
    <div class="row">
        <div class="col-sm-6"><?php echo $this->form->GradeID; ?></div>
        <div class="col-sm-6"><?php echo $this->form->LearnerNumber; ?></div>
    </div>
    
    <?php if (isset($edit)): ?>
    
    <div class="row">
        <div class="col-sm-6"><?php echo $this->form->Email; ?></div>
        <div class="col-sm-6"><?php echo $this->form->Password; ?></div>
    </div>
    
    <?php else: ?>
    
    <div class="row">
        <div class="col-sm-6"><?php echo $this->form->Email; ?></div>
        <div class="col-sm-6"><?php echo $this->form->EmailC; ?></div>
    </div>
    
    <div class="row">
        <div class="col-sm-6"><?php echo $this->form->Password; ?></div>
        <div class="col-sm-6"><?php echo $this->form->PasswordC; ?></div>
    </div>
    
    <?php endif; ?>
    
</form>

<script type="text/javascript">
$(function() {
    $('#Password, #PasswordC').val('').prop('autocomplete', 'off');
});
</script>