<div class="container">

    <div class="row">
    
        <div class="col-sm-3 sidebar">
            <?php 
                $navigation = $this->navigation()->findOneById('nav-account');
                echo $this->navigation()->menu()->renderPartial($navigation, array('partial/sidebar-nav.phtml', 'default'));
            ?>
        </div>
        
        <div class="col-sm-9">
        
            <h3><?php echo $this->translate('My Children'); ?></h3>
            
            <?php if ($this->children): ?>
            
                <?php $key_grade = 'Grade_' . $this->lang; ?>
            
                <table class="table table-striped">
                <thead>
                <tr>
                    <th><?php echo $this->translate('Grade'); ?></th>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('Learner Number'); ?></th>
                    <th><?php echo $this->translate('Email Address'); ?></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->children as $item): ?>
                    <tr>
                        <td><?php echo $this->escape($item->{$key_grade}); ?>
                        <td><?php echo $this->escape($item->FullName); ?></td>
                        <td><?php echo $this->escape($item->LearnerNumber); ?></td>
                        <td><?php echo $this->escape($item->Email); ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(array('reference' => $item->StudentUniqueRef), 'account-child'); ?>" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="<?php echo $this->translate('edit'); ?>">
                                <span class="fa-stack">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            <a href="<?php echo $this->url(array('reference' => $item->StudentUniqueRef), 'account-child-subject'); ?>" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="<?php echo $this->translate('manage subjects'); ?>">
                                <span class="fa-stack">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-cogs fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
                </table>
            
            <?php else: ?>
            
                <p><?php echo $this->translate('There are currently no student accounts linked to you.'); ?></p>
            
            <?php endif; ?>
            
            <br>
            
            <div class="clearfix">
            
                <a class="btn btn-primary" href="user/student/add" data-toggle="modal" data-target="#modal">
                    <?php echo $this->translate('New Student Account'); ?>
                </a>
                <a class="btn btn-default" href="user/student/link" data-toggle="modal" data-target="#modal">
                    <?php echo $this->translate('Link Existing Account'); ?>
                </a>
            
            </div>
            
        </div>
        
    </div>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/jquery.form.min.js"></script>
<script>
$(function() {

    var $btn;
	
	$('.ajax-form').ajaxForm({
	    delegation: true,
		dataType: 'json',
		beforeSubmit: function(data, form, options) {
		    $btn = form.closest('.modal').find('[type="submit"]');
		    $btn.attr('data-text', $btn.text()).prop('disabled', 'disabled').text('<?php echo $this->translate('Please wait'); ?>');
			form.find('.has-feedback').removeClass('has-feedback has-error').find('.help-error').remove();
		},
		success: function(response, status, xhr, form) {

			if (response.result === 0) {
				if (response.formErrors) {
					$.each(response.formErrors, function(k, v) {
						var control = form.find('#' + k).closest('.form-group');
						control.addClass('has-feedback has-error');
						control.find('label').next('div').append('<span class="help-block help-error">' + v + '</span>');
					});
				}
			}

			if (response.callback) {
			    evalCallback(response.callback);
			}

			return;
		},
		error: function(xhr, status, error) {
		    displayMessage(error, 'An unknown error occurred. Please contact us for further assistance.');
		},
		complete: function(xhr, status) {
			$btn.prop('disabled', false).text($btn.attr('data-text'));    
		}
	});

});
function formSuccess() {
    location.href = document.location;
};
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>