<div class="container">

    <h3><?php echo $this->translate('My order'); ?></h3>
        
    <?php 
        $grand       = 0;
        $lang_suffix = $this->lang === 'AFR' ? '_af' : null;
    ?>

    
    <div class="seperator seperator-large"></div>
    
    <h3><?php echo $this->translate('Payment'); ?></h3>
    <p><?php echo $this->translate('Please select your preferred payment method below.'); ?></p> <hr> <br>
    
    <form method="post">
    
        <?php echo $this->form->paytype; ?>
        
        <?php /*
        
        <div id="paytype-info" class="paytype-info">
            <div class="paytype-info-item" data-type="cash">
                <?php echo $this->translate('Some description here of how the CASH payment option works...'); ?>        
            </div>
            <div class="paytype-info-item" data-type="cheque">
                <?php echo $this->translate('Some description here of how the CHEQUE payment option works...'); ?>        
            </div>
            <div class="paytype-info-item" data-type="card">
                <?php echo $this->translate('Some description here of how the CREDIT CARD payment option works...'); ?>        
            </div>
            <div class="paytype-info-item" data-type="eft">
                <?php echo $this->translate('Some description here of how the EFT payment option works...'); ?>        
            </div>
        </div>
        
        */ ?>
        
        <?php echo $this->form->submit; ?>
    
    </form>

</div>

<?php echo $this->placeholder('deferred')->captureStart(); ?>
<script>
$(function() {
    <?php /*
    $('#paytype').on('change', function() {
        $('.paytype-info-item').css('display', 'none');
        $('.paytype-info-item[data-type="' + $(this).val() + '"]').css('display', 'block');
    }).change();
    */ ?>
});
</script>
<?php echo $this->placeholder('deferred')->captureEnd(); ?>