<div class="container">

    <h3><?php echo $this->translate('My order'); ?></h3>
        
    <?php 
        $grand       = 0;
        $lang_suffix = $this->lang === 'AFR' ? '_af' : null;
    ?>

    
    <div class="seperator seperator-large"></div>
    
    <h3><?php echo $this->translate('Payment'); ?></h3>
    
    <form method="post">
        <p>
            Click next to sign into cloudbanc
        </p>
        


        <?php echo $this->form->submit; ?>
    
    </form>

</div>

<?php echo $this->placeholder('deferred')->captureStart(); ?>
<script>
$(function() {
    <?php /*
    $('#paytype').on('change', function() {
        $('.paytype-info-item').css('display', 'none');
        $('.paytype-info-item[data-type="' + $(this).val() + '"]').css('display', 'block');
    }).change();
    */ ?>
});
</script>
<?php echo $this->placeholder('deferred')->captureEnd(); ?>