<?php //Zend_Debug::dump($this->items);?>
<div class="container">

    <h3><?php echo $this->translate('Checkout'); ?></h3>
        
    <?php if ($this->items): ?>
        <p><?php echo $this->translate('Please find the contents of your shopping cart below.'); ?></p>
        <?php 
            $grand       = 0;
            $lang_suffix = $this->lang === 'AFR' ? '_af' : null;
        ?>
    

        <?php

        foreach ($this->sortedItems as $name => $cartItem) {
            $sub = 0;
            ?>
            <h2><?php echo $name; ?></h2>
            <table class="table table-striped table-item">
            <thead>
            <tr>
                <th><?php echo $this->translate('Student'); ?></th>
                <th><?php echo $this->translate('Item'); ?></th>
                <th><?php echo $this->translate('Price'); ?></th>
                <th><?php echo $this->translate('Qty'); ?></th>
                <th><?php echo $this->translate('Total'); ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($cartItem as $item):
                $grand += $item['total'];
                $sub += $item['total'];
                ?>
                <tr data-id="<?php echo $item['id']; ?>" data-sid="<?php echo $item['id']; ?>" data-qty="<?php echo $item['qty']; ?>" data-total="<?php echo $item['total']; ?>">
                    <td>
                        <?php if ($item['student_id']): ?>
                            <?php echo $this->escape($item['student_name']); ?>
                        <?php else: ?>
                            N/A
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->escape($item['name' . $lang_suffix]); ?></td>
                    <td><?php echo $this->currency($item['price']); ?></td>
                    <td><input type="text" name="qty" value="<?php echo $item['qty']; ?>" maxlength="2" size="4"></td>
                    <td>
                        <span class="total"><?php echo $this->currency($item['total']); ?></span>
                    </td>
                    <td class="text-center"><a href="javascript:;" class="cart-remove" tabIndex="-1"><i class="fa fa-times text-danger"></i></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <th colspan="4" style="text-align: right">Sub Total</th>
                <th colspan="2">
                    <span class="grand-total" id="grand-total"><?php echo $this->currency($sub); ?></span>
                </th>
            </tr>
            </tfoot>
            </table> <br>
        <?php } ?>
            <table class="table table-striped table-item">
                <tr>
                    <td style="text-align: right; font-weight: bold"><span class="total">Total: <?php echo $this->currency($grand); ?></span></td>
                </tr>
            </table>
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <p><a href="checkout/confirm" class="btn btn-primary"><?php echo $this->translate('Continue to payment'); ?></a></p>
             <div class="seperator seperator-large"></div>
        <?php else: ?>
            <?php 
                $url_login     = $this->url(array(), 'login');
                $url_register  = $this->url(array(), 'register');
                $link_login    = '<a href="' . $url_login . '?redir=checkout">' . $this->translate('login') . '</a>';
                $link_register = '<a href="' . $url_register . '?redir=checkout">' . $this->translate('register') . '</a>';
            ?>
        
            <p class="text-center"><?php echo sprintf($this->translate('Please %s or %s to continue.'), $link_login, $link_register); ?></p>
        
        <?php endif; ?>
    
    <?php else: ?>
    
        <p><?php echo $this->translate('Your shopping cart is empty.'); ?></p>
    
    <?php endif; ?>  
			<button id="btn-Back" class="btn btn-primary pull-right" data-type="stock" type="button" onclick="goBack()">
                        <?php echo $this->translate('Go Back'); ?>
                    </button>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/accounting/accounting.min.js"></script>
<script>
$(function() {
    $('input[name="qty"]').on('focus', function() {
        $(this).attr('data-qty', accounting.formatNumber($(this).val(), 0, ''))
    }).on('blur', function(e) {
        if ($(this).val() != $(this).closest('tr').attr('data-qty'))
     	   setQty($(this));
    }).on('keypress', function(e) {
    	var keycode = (e.keyCode ? e.keyCode : e.which);
    	if (keycode == '13')
        	setQty($(this));
    });
	$('.cart-remove').on('click', function(e) {
		e.preventDefault();
		if (window.confirm("<?php echo $this->translate('Are you sure you want to remove item form cart?'); ?>")) {       
		var $tr = $(this).closest('tr');
		$.getJSON('cart/remove', { id: $tr.data('id') }, function(data) {
			var $table = $tr.closest('table');
			if ($table.find('tbody tr').length <= 2) {
				location.href = document.location;
			} else {
			    $tr.remove(); setTotal();
			}
		});
		}		
	});

});
function setQty(obj)
{
    var $tr    = obj.closest('tr'),
        $input = $tr.find('[name="qty"]'),
        $qty   = accounting.formatNumber($input.val(), 0, '');

    $input.val($qty);

    if ($qty <= 0)
        return;

    $.getJSON('cart/update', { id: $tr.data('id'), qty: $qty }, function(data) {
        if (data.result === 1) {
            $tr.attr('data-total', data.total).attr('data-qty', $qty);
            $tr.find('.total').text(accounting.formatMoney(data.total, 'R', 2, ' ', ','));
            setTotal();
        }
    });
}
function setTotal()
{
    var $total = 0;
	$('tr[data-total]').each(function() {
	    $total = $total + parseFloat(accounting.formatNumber($(this).attr('data-total'), 2, ''));
	});
	$('#grand-total').text(accounting.formatMoney($total, 'R', 2, ' ', ','));
}
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>