<div class="container">

    <div class="row">
    
        <div class="col-md-6">
        
            <h3><?php echo $this->translate('Login to your account'); ?></h3>
            
            <?php echo $this->form; ?>
            <p><a href="<?php echo $this->url(array(), 'forgot-password'); ?>"><?php echo $this->translate('Forgotten your password?'); ?></a></p>
        
        </div>
    
        <div class="col-md-6">
        
            <h3><?php echo $this->translate('New User'); ?></h3>
            <p><?php echo $this->translate('Dont\' have an account?'); ?> <a href="<?php echo $this->url(array(), 'register'); ?>"><?php echo $this->translate('Register'); ?></a></p>            
                
        </div>
        
    </div>

</div>