<?php ?>
<div class="container">

    <div class="row">
    
        <div class="col-sm-4 col-lg-3">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Packages'); ?></h3>
                
                <?php $key_name = 'Description_' . $this->lang; ?>
                
                <nav>
                    <ul class="navigation">
                    <?php foreach ($this->bundles as $bundle): ?>
                    <li>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-id="<?php echo $bundle->PriceListID; ?>">
                                <?php echo $this->escape($bundle->{$key_name}); ?>
                            </label>
                        </div>
                        
                    </li>
                    <?php endforeach; ?>
                    </ul>
                </nav>
                
            </div>
            
        </div>
        
        <div class="col-sm-8 col-lg-9">
        
            <h3><?php echo $this->translate('Product Packages'); ?> - <?php echo $this->escape($this->student->FullName); ?></h3>
            
            <p class="bundles-checked">
                <?php echo $this->translate('If you would like to customise this order, please');
		echo ('<a href="javascript:;" id="customize" style="font-size: 20px;color:red">' . $this->translate('Click here').'</a>');
		 ?>
            </p>
            
            <p class="bundles-unchecked">
                <?php echo $this->translate('Please select one or more bundles from the options provided.'); ?>
            </p>
           
            <div class="seperator"></div> <br>
            
            <?php 
                $key_name_b = 'Description_' . $this->lang;
                $key_name_i = 'Name_' . $this->lang;
            ?>
            <div id="TotalBundel">
            <?php foreach ($this->bundles as $bundle): ?>
            
                <div id="bundle" class="bundle" data-id="<?php echo $bundle->PriceListID; ?>">
            		
                    <h4><?php echo $this->escape($bundle->{$key_name_b}); ?></h4>
                     <div><font color="red"><?php echo $bundle->Notes ?></font></div>
                    <div class="table-responsive">
                
                        <table class="table table-striped table-item">
                        <thead>
                        <tr>
                            <th style="width: 10px;" class="customize"></th>
                            <th><?php echo $this->translate('Item'); ?></th>
                            <th style="width: 100px;"><?php echo $this->translate('Type'); ?></th>
 			    <th style="width: 100px;">ISBN/BARCODE</th>
                            <th style="width: 100px;"><?php echo $this->translate('Price'); ?></th>
                            <th style="width: 60px;"><?php echo $this->translate('Qty'); ?></th>
                            <th style="width: 120px;"><?php echo $this->translate('Total'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($bundle->Items as $item): ?>
                        
                            <?php 
                            
                                $total = $item->Quantity * $item->Price;
                            
                                $props = array(
                                    'data-bid="' . $bundle->PriceListID . '"',
                                    'data-price="' . $item->Price . '"',
                                    'data-qty="' . $item->Quantity . '"',
                                    'data-qty-default="' . $item->Quantity . '"',
                                    'data-total="' . $total . '"',
                                    'data-gradeid="' . $this->GradeID . '"',
                                );
                            
                                $type_text = null; 
                               // echo $item->ProductType;
                                switch ($item->ProductType) {
                                    
                                    case 'Books':
					$props[]   = 'data-sid="' . $item->ISBN . '"';
                                        $props[]   = 'data-type="book"';
                                        $type_text = $item->ProductType == 'Books' ? $this->translate('Book') : $this->translate('eBook');
                                        break;
                                    case 'EBooks':
                                        $props[]   = 'data-sid="' . $item->ISBN . '"';
                                        $props[]   = 'data-type="book"';
                                        $type_text = $item->ProductType == 'Books' ? $this->translate('Book') : $this->translate('eBook');
					$Required = '(0)' . $this->translate('eBook');
                                        break;
                                        
                                    case 'SecondhandBooks':
                                        $props[]   = 'data-sid="' . $item->ISBN . '"';
                                        $props[]   = 'data-type="book"';
                                        $props[]   = 'data-second-hand="true"';
                                        $type_text = $this->translate('Book') . ' <span class="label label-success">' . $this->translate('2nd Hand') . '</span>';
                                        break;
                                        
                                    default:
                                        $props[]   = 'data-sid="' . $item->StockID . '"';
                                        $props[]   = 'data-type="stock"';
                                        $type_text = $this->translate('Stationery');
                                        break;
                                    
                                }
                                
                            ?>
                            
                            <tr <?php echo implode(' ', $props); ?>>
                                <td class="customize">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="custom-item">
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <?php echo $this->escape($item->{$key_name_i}); ?>
                                    <span class="tiny"><?php
					 if( $item->ProductType === "EBooks")
					 {
					  echo '( '. $this->translate('Optional'). ' )';
                                         }
				         else{ 
					 echo '( ' .$this->escape($item->Quantity) . ' ';
					echo $this->translate('required') . ' )';
					 }
					 ?></span>
                                </td>
                                <td>
                                    <?php echo $type_text; ?>
                                </td>
				<td><?php	 if( $item->ProductType === "Product")
						 {
					  	 echo $item->Barcode;
                                        	 }
				        	 else{
						 echo $item->ISBN;
						}?>
				</td>
                                <td><?php echo $this->currency($item->Price); ?></td>
                                <td>
                                    <span class="custom-no"><?php echo $item->Quantity; ?></span>
                                    <span class="custom hide"><input type="text" name="qty" value="<?php echo $item->Quantity; ?>" maxlength="2" size="4"></span>
                                </td>
                                <td>
                                    <span class="total"><?php echo $this->currency($total); ?></span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        </table> 
                    
                    </div>
                    
                    <div class="seperator"></div>
                    
                    <br>
                    
                </div>
            
            <?php endforeach; ?>
            </div>
            <div class="bundles-checked">
            
                <div class="clearfix">
                
                    <h4 class="pull-left">
                        <?php echo $this->translate('Total'); ?>: 
                        <span class="grand-total" id="grand-total"></span>
                    </h4>
                <span class="pull-right">
                    <button id="cart-add" class="btn btn-primary " data-id="<?php echo $this->product->StockID; ?>" data-type="stock" type="button">
                        <?php echo $this->translate('Add to Cart'); ?>
                    </button>
		 &nbsp;
		   <button id="cart-view" class="btn btn-primary " data-id="<?php echo $this->product->StockID; ?>" data-type="stock" type="button">
                        <?php echo $this->translate('Go to Cart'); ?>
                    </button>
		 &nbsp;
		   <button id="cart-print" class="btn btn-primary pull-right" data-id="<?php echo $this->product->StockID; ?>" data-type="stock" type="button">
                        <?php echo $this->translate('Print Packages'); ?>
                    </button>

		</span>
                
                </div>
            
            </div>
            
        </div>
                                                                            
    </div>

</div>

<?php $this->placeholder('deferred')->captureStart(); ?>
<script type="text/javascript" src="js/vendor/accounting/accounting.min.js"></script>
<script type="text/javascript" src="js/vendor/tinysort/jquery.tinysort.min.js"></script>
<script type="text/javascript" src="js/vendor/tinysort/jquery.tinysort.charorder.min.js"></script>
<script>
$(function() {

	$('.table > tbody > tr').tsort('td:eq(2)', 'td:eq(1)');
	
	$('.customize, tr[data-second-hand]').hide();

    // second hand books

    $('.bundle').each(function() {

    	if ($(this).find('tr[data-second-hand]').length) {
    	    $html = '<p><span class="label label-primary"><?php echo $this->translate('Please Note') ?></span> <?php echo sprintf($this->translate('Second hand books are available in this bundle. %s to toggle these items on/off.'), '<a href="javascript:;" class="second-hand">' . $this->translate('Click here') . '</a>'); ?></p>';
    	    $(this).find('h4').after($html);
    	}
    	
    });

    $('.second-hand').on('click', function(e) {
        var $bundle = $(this).closest('.bundle');
        $bundle.find('tr[data-second-hand]').each(function() {
            $(this).toggle();
            setLineTotal($(this));
        });
    });
    
    // end
	
    $('nav :checkbox').on('change', function(e) {
    	var $bundle = $('.bundle[data-id="' + $(this).data('id') + '"]');
    	$(this).is(':checked') ? $bundle.show() : $bundle.hide();
    	toggleHelpers();
    	setGrandTotal();
    });

    $('#customize').on('click', function(e) {

        e.preventDefault();
        $(this).toggleClass('selected');

        if ($(this).hasClass('selected')) {
        
            $('.customize').show();
            $('tr[data-sid]').each(function() {
                $(this).find('.custom-no').text(0);
                $(this).find('input[name="qty"]').val(0);
                setLineTotal($(this));
            });

        } else {

            $('.customize').hide();
            $('tr[data-sid]').each(function() {
            	$(this).find('.custom-item').attr('checked', false);
                $(this).find('.custom-no').show().text($(this).data('qty-default'));
                $(this).find('.custom').addClass('hide').find('input').val($(this).data('qty-default'));
                setLineTotal($(this));
            });
        	
        }
        
    });

    $(':checkbox.custom-item').on('click', function(e) {

    	var $tr = $(this).closest('tr');

        if ($(this).is(':checked')) {
            $tr.find('.custom-no').hide();
            $tr.find('.custom').removeClass('hide').find('input').val($tr.data('qty-default'));
        } else {
            $tr.find('.custom-no').show();
            $tr.find('.custom').addClass('hide').find('input').val(0);
        }
        
        setLineTotal($tr);
        
    });

    $('input[name="qty"]').on('focus', function() {
        $(this).attr('data-qty', accounting.formatNumber($(this).val(), 0, ''));
    }).on('blur', function(e) {
        if ($(this).val() != $(this).closest('tr').attr('data-qty'))
     	   setLineTotal($(this).closest('tr'));
    }).on('keypress', function(e) {
    	var keycode = (e.keyCode ? e.keyCode : e.which);
    	if (keycode == '13')
    		setLineTotal($(this).closest('tr'));
    });
    $('#cart-view').on('click', function(e) {
	window.location.href  = "checkout";
	});

    $('#cart-print').on('click', function(e) {
	printOrder();
	});

    
    $('#cart-add').on('click', function(e) {

        var $data = [], $this = $(this);

    	$('.bundle:visible tr[data-sid]:visible').each(function() {

    	    var $id   = $(this).attr('data-sid'),
    	        $bid  = $(this).attr('data-bid'),
    	        $qty  = $(this).attr('data-qty'),
                $grade_id = $(this).attr('data-grade_id'),
    	        $type = $(this).attr('data-type');
	        
    	    if (!$id || $qty <= 0)
        	    return;

    	    var $found = null;

    	    $.each($data, function(k, v) {
    	        if (v.sid == $id) {
    	            $found = k;
    	            return false;
    	        }
    	    });
    	    
    	    if ($found !== null) {

    	        var $item = $data[$found];
    	        $item.qty = parseInt($item.qty) + parseInt($qty);
    	        $data[$found] = $item;
    	        
    	    } else {

    	    	var $item = { sid: $id, qty: $qty, type: $type, bundle_id: $bid , grade_id : $grade_id};

        	    <?php if ($this->auth->AccountType === 'Parent'): ?>
        	    $item.student_id   = '<?php echo $this->student->StudentUniqueRef; ?>';
        	    $item.student_name = '<?php echo $this->student->FullName; ?>';
        	    <?php endif; ?>

        	    $data.push($item);
    	    	
    	    }
    	    
    	});

        $.ajax('cart/add', {
            type: 'post',
        	data: JSON.stringify($data),
        	contentType: 'application/json; charset=UTF-8',
        	beforeSend: function() {
        	    $this.attr('data-text', $this.text()).prop('disabled', 'disabled').text('<?php echo $this->translate('Please wait...'); ?>');
        	} 
        }).done(function(data, status, xhr) {
            if (data.result === 1) {
                displayMessage(data.message, 'success');
            }
        }).always(function() {
        	$this.prop('disabled', false).text($this.attr('data-text'));
        });

        e.preventDefault();
        
    });
    
    toggleHelpers();
});

function setLineTotal(obj)
{
    var $input = obj.find('[name="qty"]'),
        $qty   = accounting.formatNumber($input.val(), 0, '');

    $input.val($qty);

    var $price = accounting.formatNumber(obj.data('price'), 2, '');
    var $total = $price * $qty;

    obj.find('.total').text(accounting.formatMoney($price * $qty, 'R', 2, ' ', ','));
    obj.attr('data-total', $total).attr('data-qty', $qty);

    setGrandTotal();
}

function setGrandTotal()
{
    var $total = 0;
	$('.bundle:visible tr[data-total]:visible').each(function() {
	    $total = $total + parseFloat(accounting.formatNumber($(this).attr('data-total'), 2, ''));
	});
	$('#grand-total').text(accounting.formatMoney($total, 'R', 2, ' ', ','));
}

function toggleHelpers()
{
	$('.bundles-checked, .bundles-unchecked').hide();
	$('.bundle:visible').length ? $('.bundles-checked').show() : $('.bundles-unchecked').show();
}
</script>
<?php $this->placeholder('deferred')->captureEnd(); ?>