<div class="container">

    <div class="row">
    
        <div class="col-sm-8 col-lg-9 col-sm-push-4 col-lg-push-3">
        
            <div class="row product-view">
            
                <div class="col-sm-4">
                    <div class="item-image">
                        <img class="img-responsive" src="<?php echo $this->book->ImageURLBig; ?>">
                    </div>
                </div>
            
                <div class="col-sm-8">
                
                    <?php 
                        $key_desc = 'Description_' . $this->lang;
                    ?>
                
                    <h3><?php echo $this->escape($this->book->Name); ?></h3>
                    <h4><?php echo $this->currency($this->book->Price); ?></h4>
                    <h5>ISBN : <?php echo $this->book->ISBN; ?></h5>
                    <p><?php echo $this->escape($this->book->{$key_desc}); ?></p>
                    
                    <hr>
                    
                    <button id="cart-add" class="btn btn-primary cart-add" data-id="<?php echo $this->book->ISBN; ?>" data-type="book" type="button">
                        <?php echo $this->translate('Add to Cart'); ?>
                    </button>
                    
                </div>
                
            </div>
        
        </div>
        
        <div class="col-sm-4 col-lg-3 col-sm-pull-8 col-lg-pull-9">
        
            <div class="sidebar">
        
                <h3><?php echo $this->translate('Categories'); ?></h3>
                <?php 
                    $navigation = $this->navigation()->findOneById('nav-book');
                    echo $this->navigation()->menu()->renderPartial($navigation, array('partial/sidebar-nav.phtml', 'default'));
                ?>
                
            </div>
            
        </div>
        
    </div>

    <?php // Zend_Debug::dump($this->product); ?>

</div>